/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import database.dbkoneksi;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class pengeluaran extends javax.swing.JFrame {

    Connection connect;
    Statement st;
    ResultSet rs;
    dbkoneksi koneksi;
    int userId;
    String NamaBarang, Deskripsi, Kategori, Keterangan;
    int Nominal;
    /**
     * Creates new form pengeluaran
     */
    public pengeluaran() {
        initComponents();
    }

    public pengeluaran(int userId) {
        initComponents();
        koneksi = new dbkoneksi();
        connect = koneksi.getConnection();
        this.userId = userId;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        Label_Nominal = new javax.swing.JLabel();
        Field_Nominal = new javax.swing.JTextField();
        Label_NamaBarang = new javax.swing.JLabel();
        Field_NamaBarang = new javax.swing.JTextField();
        Label_Deskripsi = new javax.swing.JLabel();
        Field_Deskripsi = new javax.swing.JTextField();
        Box_Kategori = new javax.swing.JComboBox<>();
        Label_Kategori = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(640, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        txtTitle.setText("Pengeluaran");
        txtTitle.setToolTipText("");

        Label_Nominal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_Nominal.setForeground(new java.awt.Color(153, 153, 153));
        Label_Nominal.setText("Nominal");

        Field_Nominal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Field_Nominal.setBorder(null);
        Field_Nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_NominalActionPerformed(evt);
            }
        });

        Label_NamaBarang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_NamaBarang.setForeground(new java.awt.Color(153, 153, 153));
        Label_NamaBarang.setText("Nama Barang");

        Field_NamaBarang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Field_NamaBarang.setBorder(null);
        Field_NamaBarang.setMaximumSize(new java.awt.Dimension(241, 41));
        Field_NamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_NamaBarangActionPerformed(evt);
            }
        });

        Label_Deskripsi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_Deskripsi.setForeground(new java.awt.Color(153, 153, 153));
        Label_Deskripsi.setText("Deskripsi Barang");

        Field_Deskripsi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Field_Deskripsi.setBorder(null);
        Field_Deskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_DeskripsiActionPerformed(evt);
            }
        });

        Box_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori 1", "Kategori 2", "Kategori 3", "Kategori 4" }));
        Box_Kategori.setBorder(null);
        Box_Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_KategoriActionPerformed(evt);
            }
        });

        Label_Kategori.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_Kategori.setForeground(new java.awt.Color(153, 153, 153));
        Label_Kategori.setText("Pilih Kategori");

        jButton1.setBackground(new java.awt.Color(41, 100, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Selesai");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Field_Nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitle)
                            .addComponent(Label_Nominal))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_NamaBarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Field_NamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Box_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Kategori)
                            .addComponent(Label_Deskripsi)
                            .addComponent(Field_Deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Nominal)
                    .addComponent(Label_NamaBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field_Nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field_NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Label_Deskripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Kategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Box_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_NominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_NominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_NominalActionPerformed

    private void Field_NamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_NamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_NamaBarangActionPerformed

    private void Field_DeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_DeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_DeskripsiActionPerformed

    private void Box_KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_KategoriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!checkInput()) {
        return;
        }
        NamaBarang = Field_NamaBarang.getText();
        Deskripsi = Field_Deskripsi.getText();
        Kategori = Box_Kategori.getSelectedItem().toString();
        Nominal = Integer.parseInt(Field_Nominal.getText());
        insertInput(NamaBarang, Deskripsi, Kategori, Nominal);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengeluaran().setVisible(true);
            }
        });
    }

    private boolean checkInput() {
        NamaBarang = Field_NamaBarang.getText();
        Deskripsi = Field_Deskripsi.getText();
        Kategori = Box_Kategori.getSelectedItem().toString();
        String nominalText = Field_Nominal.getText();
        if (!nominalText.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Nominal harus berupa angka");
            return false;
        }
        if (NamaBarang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Barang belum diisi");
            return false;
        }
        if (Deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Deskripsi belum diisi");
            return false;
        } 
        if (Kategori.equals("Pilih Kategori")) {
            JOptionPane.showMessageDialog(this, "Kategori belum dipilih");
            return false;
        }
    return true;
}

    private void insertInput(String NamaBarang, String Deskripsi, String Kategori, int Nominal) {
        String sqlInsert = "INSERT INTO pengeluaran (IdUser, NamaBarang, Nominal, Kategori, Deskripsi, Keterangan, "
                + "Tanggal) VALUES (?, ?, ?, ?, ?, ?, CURRENT_DATE)";
    
        try (PreparedStatement ps = connect.prepareStatement(sqlInsert)) {
        ps.setInt(1, userId);
        ps.setString(2, NamaBarang);
        ps.setInt(3, Nominal);
        ps.setString(4, Kategori);
        ps.setString(5, Deskripsi);
        ps.setString(6, "Pengeluaran");
        
        int rowsInserted = ps.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            // Clear the fields after successful insert
            Field_NamaBarang.setText("");
            Field_Nominal.setText("");
            Field_Deskripsi.setText("");
            Box_Kategori.setSelectedIndex(0);
        }
        dashboard select = new dashboard(userId);
        this.setVisible(false);
        select.setVisible(true);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_Kategori;
    private javax.swing.JTextField Field_Deskripsi;
    private javax.swing.JTextField Field_NamaBarang;
    private javax.swing.JTextField Field_Nominal;
    private javax.swing.JLabel Label_Deskripsi;
    private javax.swing.JLabel Label_Kategori;
    private javax.swing.JLabel Label_NamaBarang;
    private javax.swing.JLabel Label_Nominal;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
